"""Agregar tabla public_messages para mensajes públicos

Revision ID: 418b8ebc4838
Revises: 0924117de109
Create Date: 2025-02-19 16:51:23.466401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418b8ebc4838'
down_revision = '0924117de109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('tematica', sa.String(length=100), nullable=False),
    sa.Column('idioma', sa.String(length=50), nullable=False),
    sa.Column('contestado', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_messages')
    # ### end Alembic commands ###
