"""Agregar campo responder_id a PublicMessage

Revision ID: 4c21bd73b5dd
Revises: 230b1a262c67
Create Date: 2025-02-22 10:53:46.011337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c21bd73b5dd'
down_revision = '230b1a262c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responder_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_messages', schema=None) as batch_op:
        batch_op.drop_column('responder_id')

    # ### end Alembic commands ###
